# Generated by Django 4.0.3 on 2023-01-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_alter_salesrecord_automobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='price',
            field=models.PositiveBigIntegerField(),
        ),
    ]
